/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/IconMongoDB.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CompIcons {
  CompIcons._();

  static const _kFontMongoDB = 'IconMongoDB';
  static const _kFontDart = 'IconDart';
  static const _kFontFirebase = 'IconFirebase';
  static const _kFontFlutter = 'IconFlutter';
  static const String? _kFontPkg = null;

  static const IconData mongodb =
      IconData(0xe800, fontFamily: _kFontMongoDB, fontPackage: _kFontPkg);
  static const IconData dart =
      IconData(0xe801, fontFamily: _kFontDart, fontPackage: _kFontPkg);
  static const IconData firebase =
      IconData(0xe803, fontFamily: _kFontFirebase, fontPackage: _kFontPkg);
  static const IconData flutter =
      IconData(0xe809, fontFamily: _kFontFlutter, fontPackage: _kFontPkg);
}
